[program:voice_light_train_public_v4_v5]
command=/usr/bin/bash /opt/supervisor-scripts/train_public_v4_v5.sh
autostart=false
autorestart=unexpected
startsecs=1
stdout_logfile=/var/log/portal/voice_light_train_public_v4_v5.log
stderr_logfile=/var/log/portal/voice_light_train_public_v4_v5.err.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
